# Generated by Django 5.2.4 on 2025-08-28 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم نوع الرسوم', max_length=100, unique=True, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, help_text='وصف نوع الرسوم', verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, help_text='هل نوع الرسوم نشط', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء نوع الرسوم', verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع الرسوم',
                'verbose_name_plural': 'أنواع الرسوم',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم مقدم خدمة الدفع', max_length=100, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, help_text='وصف مقدم خدمة الدفع', verbose_name='الوصف')),
                ('instructions', models.TextField(help_text='تعليمات الدفع للطلاب', verbose_name='التعليمات')),
                ('is_active', models.BooleanField(default=True, help_text='هل مقدم الخدمة نشط', verbose_name='نشط')),
                ('logo', models.ImageField(blank=True, help_text='شعار مقدم خدمة الدفع', null=True, upload_to='payment_providers/', verbose_name='الشعار')),
                ('university_account_name', models.CharField(blank=True, help_text='اسم صاحب حساب الجامعة', max_length=200, null=True, verbose_name='اسم حساب الجامعة')),
                ('university_account_number', models.CharField(blank=True, help_text='رقم حساب الجامعة', max_length=100, null=True, verbose_name='رقم حساب الجامعة')),
                ('university_phone', models.CharField(blank=True, help_text='رقم هاتف الجامعة لهذا المقدم', max_length=20, verbose_name='هاتف الجامعة')),
                ('additional_info', models.TextField(blank=True, help_text='معلومات حساب إضافية (IBAN، رقم التوجيه، إلخ)', verbose_name='معلومات إضافية')),
            ],
            options={
                'verbose_name': 'مقدم خدمة الدفع',
                'verbose_name_plural': 'مقدمو خدمات الدفع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('yearly', 'Yearly Report')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_fees_issued', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_payments_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_pending_verification', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('report_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(max_length=200)),
                ('payment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('sender_name', models.CharField(blank=True, help_text='Name of person who sent the money', max_length=200, null=True)),
                ('sender_phone', models.CharField(blank=True, help_text='Phone number of sender', max_length=20, null=True)),
                ('transfer_notes', models.TextField(blank=True, help_text='Additional notes from student about the transfer')),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.paymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='financial.payment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ الرسوم', max_digits=10, verbose_name='المبلغ')),
                ('due_date', models.DateField(help_text='تاريخ استحقاق الدفع', verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('pending', 'في انتظار الدفع'), ('paid', 'مدفوع'), ('overdue', 'متأخر'), ('cancelled', 'ملغي'), ('partial', 'مدفوع جزئياً')], default='pending', help_text='حالة الرسوم', max_length=15, verbose_name='الحالة')),
                ('description', models.TextField(blank=True, help_text='وصف الرسوم', verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء الرسوم', verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(help_text='الموظف الذي أنشأ الرسوم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fees', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('fee_type', models.ForeignKey(help_text='نوع الرسوم', on_delete=django.db.models.deletion.CASCADE, to='financial.feetype', verbose_name='نوع الرسوم')),
                ('student', models.ForeignKey(help_text='الطالب المخصص له الرسوم', on_delete=django.db.models.deletion.CASCADE, related_name='fees', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'رسوم الطالب',
                'verbose_name_plural': 'رسوم الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.studentfee'),
        ),
    ]
