# Generated by Django 5.2.4 on 2025-08-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Name of person who sent the money', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_phone',
            field=models.CharField(blank=True, help_text='Phone number of sender', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_notes',
            field=models.TextField(blank=True, help_text='Additional notes from student about the transfer'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional account information (IBAN, routing number, etc.)'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='university_account_name',
            field=models.CharField(blank=True, help_text='University account holder name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='university_account_number',
            field=models.CharField(blank=True, help_text='University account number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='university_phone',
            field=models.CharField(blank=True, help_text='University phone number for this provider', max_length=20),
        ),
    ]
