# Generated by Django 5.2.4 on 2025-08-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_payment_sender_name_payment_sender_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['name'], 'verbose_name': 'نوع الرسوم', 'verbose_name_plural': 'أنواع الرسوم'},
        ),
        migrations.AlterModelOptions(
            name='paymentprovider',
            options={'ordering': ['name'], 'verbose_name': 'مقدم خدمة الدفع', 'verbose_name_plural': 'مقدمو خدمات الدفع'},
        ),
        migrations.AlterModelOptions(
            name='studentfee',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسوم الطالب', 'verbose_name_plural': 'رسوم الطلاب'},
        ),
        migrations.AlterField(
            model_name='feetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء نوع الرسوم', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='description',
            field=models.TextField(blank=True, help_text='وصف نوع الرسوم', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل نوع الرسوم نشط', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='name',
            field=models.CharField(help_text='اسم نوع الرسوم', max_length=100, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='additional_info',
            field=models.TextField(blank=True, help_text='معلومات حساب إضافية (IBAN، رقم التوجيه، إلخ)', verbose_name='معلومات إضافية'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='description',
            field=models.TextField(blank=True, help_text='وصف مقدم خدمة الدفع', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='instructions',
            field=models.TextField(help_text='تعليمات الدفع للطلاب', verbose_name='التعليمات'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل مقدم الخدمة نشط', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='logo',
            field=models.ImageField(blank=True, help_text='شعار مقدم خدمة الدفع', null=True, upload_to='payment_providers/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='name',
            field=models.CharField(help_text='اسم مقدم خدمة الدفع', max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='university_account_name',
            field=models.CharField(blank=True, help_text='اسم صاحب حساب الجامعة', max_length=200, null=True, verbose_name='اسم حساب الجامعة'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='university_account_number',
            field=models.CharField(blank=True, help_text='رقم حساب الجامعة', max_length=100, null=True, verbose_name='رقم حساب الجامعة'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='university_phone',
            field=models.CharField(blank=True, help_text='رقم هاتف الجامعة لهذا المقدم', max_length=20, verbose_name='هاتف الجامعة'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='مبلغ الرسوم', max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء الرسوم', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='created_by',
            field=models.ForeignKey(help_text='الموظف الذي أنشأ الرسوم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fees', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='description',
            field=models.TextField(blank=True, help_text='وصف الرسوم', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='due_date',
            field=models.DateField(help_text='تاريخ استحقاق الدفع', verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='fee_type',
            field=models.ForeignKey(help_text='نوع الرسوم', on_delete=django.db.models.deletion.CASCADE, to='financial.feetype', verbose_name='نوع الرسوم'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='status',
            field=models.CharField(choices=[('pending', 'في انتظار الدفع'), ('paid', 'مدفوع'), ('overdue', 'متأخر'), ('cancelled', 'ملغي'), ('partial', 'مدفوع جزئياً')], default='pending', help_text='حالة الرسوم', max_length=15, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(help_text='الطالب المخصص له الرسوم', on_delete=django.db.models.deletion.CASCADE, related_name='fees', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
    ]
