# Generated by Django 5.2.4 on 2025-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.CharField(default='MY-UNIV-001', max_length=20, unique=True),
        ),
    ]
