# Generated by Django 5.2.4 on 2025-08-27 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_university_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['employee_id'], 'verbose_name': 'الملف الشخصي للموظف', 'verbose_name_plural': 'الملفات الشخصية للموظفين'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['student_id_number'], 'verbose_name': 'الملف الشخصي للطالب', 'verbose_name_plural': 'الملفات الشخصية للطلاب'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['university_id'], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(help_text='رقم الموظف الفريد', max_length=20, unique=True, verbose_name='رقم الموظف'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='hire_date',
            field=models.DateField(help_text='تاريخ بداية العمل في الجامعة', verbose_name='تاريخ التوظيف'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='صلاحيات الموظف في النظام', verbose_name='الصلاحيات'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='الراتب الشهري للموظف', max_digits=10, null=True, verbose_name='الراتب'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(help_text='المستخدم المرتبط بهذا الملف الشخصي', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='اسم الشخص المراد الاتصال به في حالات الطوارئ', max_length=100, verbose_name='اسم جهة الاتصال في حالات الطوارئ'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='رقم هاتف جهة الاتصال في حالات الطوارئ', max_length=15, verbose_name='هاتف جهة الاتصال في حالات الطوارئ'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='المعدل التراكمي للطالب', max_digits=4, null=True, verbose_name='المعدل التراكمي'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_date',
            field=models.DateField(blank=True, help_text='تاريخ التخرج المتوقع أو الفعلي', null=True, verbose_name='تاريخ التخرج'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id_number',
            field=models.CharField(help_text='رقم الطالب الفريد', max_length=20, unique=True, verbose_name='رقم الطالب'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='total_credits',
            field=models.IntegerField(default=0, help_text='العدد الإجمالي للساعات المعتمدة المكتسبة', verbose_name='إجمالي الساعات المعتمدة'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(help_text='المستخدم المرتبط بهذا الملف الشخصي', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_level',
            field=models.CharField(blank=True, help_text='المستوى الدراسي الحالي', max_length=50, verbose_name='المستوى الأكاديمي'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='تاريخ ميلاد المستخدم', null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='القسم الذي يعمل به الموظف', max_length=100, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrollment_year',
            field=models.IntegerField(blank=True, help_text='السنة التي تم فيها تسجيل الطالب', null=True, verbose_name='سنة التسجيل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, help_text='تخصص الطالب الأكاديمي', max_length=100, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='رقم الهاتف المحمول', max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='منصب الموظف في الجامعة', max_length=100, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='صورة شخصية للمستخدم', null=True, upload_to='profile_pics/', verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='رمز QR للهوية الرقمية', null=True, upload_to='qr_codes/', verbose_name='رمز الاستجابة السريعة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.CharField(default='MY-UNIV-001', help_text='الرقم الجامعي الفريد للمستخدم', max_length=20, unique=True, verbose_name='الرقم الجامعي'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'طالب'), ('staff', 'موظف'), ('admin', 'مدير')], default='student', help_text='نوع المستخدم في النظام', max_length=10, verbose_name='نوع المستخدم'),
        ),
    ]
