# Generated by Django 5.2.4 on 2025-08-28 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='تاريخ الإحصائيات', unique=True, verbose_name='التاريخ')),
                ('total_students', models.IntegerField(default=0, help_text='العدد الإجمالي للطلاب المسجلين', verbose_name='إجمالي الطلاب')),
                ('new_students_today', models.IntegerField(default=0, help_text='عدد الطلاب الذين سجلوا اليوم', verbose_name='الطلاب الجدد اليوم')),
                ('active_students', models.IntegerField(default=0, help_text='عدد الطلاب الذين دخلوا النظام اليوم', verbose_name='الطلاب النشطون')),
                ('total_requests', models.IntegerField(default=0, help_text='العدد الإجمالي لطلبات الخدمات', verbose_name='إجمالي الطلبات')),
                ('pending_requests', models.IntegerField(default=0, help_text='عدد الطلبات في انتظار المراجعة', verbose_name='الطلبات المعلقة')),
                ('approved_requests_today', models.IntegerField(default=0, help_text='عدد الطلبات التي تم اعتمادها اليوم', verbose_name='الطلبات المعتمدة اليوم')),
                ('rejected_requests_today', models.IntegerField(default=0, help_text='عدد الطلبات التي تم رفضها اليوم', verbose_name='الطلبات المرفوضة اليوم')),
                ('total_fees_collected_today', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ الإجمالي للرسوم المحصلة اليوم', max_digits=15, verbose_name='إجمالي الرسوم المحصلة اليوم')),
                ('pending_payments', models.IntegerField(default=0, help_text='عدد المدفوعات في انتظار التحقق', verbose_name='المدفوعات المعلقة')),
                ('verified_payments_today', models.IntegerField(default=0, help_text='عدد المدفوعات التي تم التحقق منها اليوم', verbose_name='المدفوعات المتحققة اليوم')),
                ('open_support_tickets', models.IntegerField(default=0, help_text='عدد تذاكر الدعم المفتوحة', verbose_name='تذاكر الدعم المفتوحة')),
                ('resolved_tickets_today', models.IntegerField(default=0, help_text='عدد تذاكر الدعم التي تم حلها اليوم', verbose_name='التذاكر المحلولة اليوم')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء السجل', verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إحصائيات لوحة التحكم',
                'verbose_name_plural': 'إحصائيات لوحة التحكم',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الإجراء السريع', max_length=100, verbose_name='الاسم')),
                ('action_type', models.CharField(choices=[('create_announcement', 'إنشاء إعلان'), ('verify_payments', 'التحقق من المدفوعات'), ('review_requests', 'مراجعة الطلبات'), ('generate_report', 'إنشاء تقرير'), ('manage_fees', 'إدارة الرسوم'), ('student_lookup', 'البحث عن طالب')], help_text='نوع الإجراء السريع', max_length=25, verbose_name='نوع الإجراء')),
                ('description', models.CharField(help_text='وصف الإجراء السريع', max_length=200, verbose_name='الوصف')),
                ('url_pattern', models.CharField(help_text='نمط الرابط للإجراء', max_length=200, verbose_name='نمط الرابط')),
                ('icon_class', models.CharField(default='fas fa-cog', help_text='فئة CSS للأيقونة', max_length=50, verbose_name='فئة الأيقونة')),
                ('is_active', models.BooleanField(default=True, help_text='هل الإجراء نشط', verbose_name='نشط')),
                ('required_permissions', models.JSONField(default=list, help_text='قائمة الصلاحيات المطلوبة', verbose_name='الصلاحيات المطلوبة')),
                ('order', models.IntegerField(default=0, help_text='ترتيب عرض الإجراء', verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'إجراء سريع',
                'verbose_name_plural': 'إجراءات سريعة',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'تسجيل دخول المستخدم'), ('logout', 'تسجيل خروج المستخدم'), ('request_approved', 'اعتماد طلب'), ('request_rejected', 'رفض طلب'), ('payment_verified', 'التحقق من دفعة'), ('payment_rejected', 'رفض دفعة'), ('document_uploaded', 'رفع مستند'), ('announcement_created', 'إنشاء إعلان'), ('notification_created', 'إنشاء إشعار'), ('report_generated', 'إنشاء تقرير'), ('fee_created', 'إنشاء رسوم'), ('user_created', 'إنشاء مستخدم'), ('user_modified', 'تعديل مستخدم'), ('other', 'نشاط آخر')], help_text='نوع النشاط المنجز', max_length=20, verbose_name='نوع النشاط')),
                ('description', models.TextField(help_text='وصف تفصيلي للنشاط', verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='عنوان IP للمستخدم', null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, help_text='معلومات المتصفح', verbose_name='وكيل المستخدم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت النشاط', verbose_name='الطابع الزمني')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='بيانات إضافية حول النشاط', verbose_name='البيانات الوصفية')),
                ('staff_member', models.ForeignKey(help_text='الموظف الذي قام بالنشاط', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='عضو الطاقم')),
                ('target_user', models.ForeignKey(blank=True, help_text='المستخدم الذي تأثر بالنشاط', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستهدف')),
            ],
            options={
                'verbose_name': 'نشاط الموظف',
                'verbose_name_plural': 'أنشطة الموظفين',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم قالب سير العمل', max_length=100, verbose_name='الاسم')),
                ('workflow_type', models.CharField(choices=[('request_processing', 'معالجة الطلبات'), ('payment_verification', 'التحقق من المدفوعات'), ('document_generation', 'إنشاء المستندات'), ('student_onboarding', 'تسجيل الطلاب الجدد'), ('fee_management', 'إدارة الرسوم')], help_text='نوع سير العمل', max_length=25, verbose_name='نوع سير العمل')),
                ('description', models.TextField(help_text='وصف سير العمل', verbose_name='الوصف')),
                ('steps', models.JSONField(default=list, help_text='قائمة خطوات سير العمل', verbose_name='الخطوات')),
                ('is_active', models.BooleanField(default=True, help_text='هل القالب نشط', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء القالب', verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(help_text='الموظف الذي أنشأ القالب', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب سير العمل',
                'verbose_name_plural': 'قوالب سير العمل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'الإعدادات العامة'), ('academic', 'الإعدادات الأكاديمية'), ('financial', 'الإعدادات المالية'), ('notification', 'إعدادات الإشعارات'), ('security', 'إعدادات الأمان')], help_text='فئة الإعداد', max_length=15, verbose_name='الفئة')),
                ('key', models.CharField(help_text='مفتاح الإعداد', max_length=100, verbose_name='المفتاح')),
                ('value', models.TextField(help_text='قيمة الإعداد', verbose_name='القيمة')),
                ('description', models.TextField(blank=True, help_text='وصف الإعداد', verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, help_text='هل الإعداد نشط', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء الإعداد', verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث')),
                ('updated_by', models.ForeignKey(help_text='الموظف الذي قام بآخر تحديث', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['category', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
