# Generated by Django 5.2.4 on 2025-08-17 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_students', models.IntegerField(default=0)),
                ('new_students_today', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('pending_requests', models.IntegerField(default=0)),
                ('approved_requests_today', models.IntegerField(default=0)),
                ('rejected_requests_today', models.IntegerField(default=0)),
                ('total_fees_collected_today', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_payments', models.IntegerField(default=0)),
                ('verified_payments_today', models.IntegerField(default=0)),
                ('open_support_tickets', models.IntegerField(default=0)),
                ('resolved_tickets_today', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('create_announcement', 'Create Announcement'), ('verify_payments', 'Verify Payments'), ('review_requests', 'Review Requests'), ('generate_report', 'Generate Report'), ('manage_fees', 'Manage Fees'), ('student_lookup', 'Student Lookup')], max_length=25)),
                ('description', models.CharField(max_length=200)),
                ('url_pattern', models.CharField(max_length=200)),
                ('icon_class', models.CharField(default='fas fa-cog', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('required_permissions', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('document_uploaded', 'Document Uploaded'), ('announcement_created', 'Announcement Created'), ('fee_created', 'Fee Created'), ('user_created', 'User Created'), ('user_modified', 'User Modified'), ('other', 'Other Activity')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workflow_type', models.CharField(choices=[('request_processing', 'Request Processing'), ('payment_verification', 'Payment Verification'), ('document_generation', 'Document Generation'), ('student_onboarding', 'Student Onboarding'), ('fee_management', 'Fee Management')], max_length=25)),
                ('description', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Settings'), ('academic', 'Academic Settings'), ('financial', 'Financial Settings'), ('notification', 'Notification Settings'), ('security', 'Security Settings')], max_length=15)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
