# Generated by Django 5.2.4 on 2025-08-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('document_uploaded', 'Document Uploaded'), ('announcement_created', 'Announcement Created'), ('notification_created', 'Notification Created'), ('report_generated', 'Report Generated'), ('fee_created', 'Fee Created'), ('user_created', 'User Created'), ('user_modified', 'User Modified'), ('other', 'Other Activity')], max_length=20),
        ),
    ]
