# Generated by Django 5.2.4 on 2025-08-27 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_panel', '0002_alter_staffactivity_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardstats',
            options={'ordering': ['-date'], 'verbose_name': 'إحصائيات لوحة التحكم', 'verbose_name_plural': 'إحصائيات لوحة التحكم'},
        ),
        migrations.AlterModelOptions(
            name='quickaction',
            options={'ordering': ['order', 'name'], 'verbose_name': 'إجراء سريع', 'verbose_name_plural': 'إجراءات سريعة'},
        ),
        migrations.AlterModelOptions(
            name='staffactivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'نشاط الموظف', 'verbose_name_plural': 'أنشطة الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={'ordering': ['name'], 'verbose_name': 'قالب سير العمل', 'verbose_name_plural': 'قوالب سير العمل'},
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='active_students',
            field=models.IntegerField(default=0, help_text='عدد الطلاب الذين دخلوا النظام اليوم', verbose_name='الطلاب النشطون'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='approved_requests_today',
            field=models.IntegerField(default=0, help_text='عدد الطلبات التي تم اعتمادها اليوم', verbose_name='الطلبات المعتمدة اليوم'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء السجل', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='date',
            field=models.DateField(help_text='تاريخ الإحصائيات', unique=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='new_students_today',
            field=models.IntegerField(default=0, help_text='عدد الطلاب الذين سجلوا اليوم', verbose_name='الطلاب الجدد اليوم'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='open_support_tickets',
            field=models.IntegerField(default=0, help_text='عدد تذاكر الدعم المفتوحة', verbose_name='تذاكر الدعم المفتوحة'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='pending_payments',
            field=models.IntegerField(default=0, help_text='عدد المدفوعات في انتظار التحقق', verbose_name='المدفوعات المعلقة'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='pending_requests',
            field=models.IntegerField(default=0, help_text='عدد الطلبات في انتظار المراجعة', verbose_name='الطلبات المعلقة'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='rejected_requests_today',
            field=models.IntegerField(default=0, help_text='عدد الطلبات التي تم رفضها اليوم', verbose_name='الطلبات المرفوضة اليوم'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='resolved_tickets_today',
            field=models.IntegerField(default=0, help_text='عدد تذاكر الدعم التي تم حلها اليوم', verbose_name='التذاكر المحلولة اليوم'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='total_fees_collected_today',
            field=models.DecimalField(decimal_places=2, default=0, help_text='المبلغ الإجمالي للرسوم المحصلة اليوم', max_digits=15, verbose_name='إجمالي الرسوم المحصلة اليوم'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='total_requests',
            field=models.IntegerField(default=0, help_text='العدد الإجمالي لطلبات الخدمات', verbose_name='إجمالي الطلبات'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='total_students',
            field=models.IntegerField(default=0, help_text='العدد الإجمالي للطلاب المسجلين', verbose_name='إجمالي الطلاب'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='verified_payments_today',
            field=models.IntegerField(default=0, help_text='عدد المدفوعات التي تم التحقق منها اليوم', verbose_name='المدفوعات المتحققة اليوم'),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='action_type',
            field=models.CharField(choices=[('create_announcement', 'إنشاء إعلان'), ('verify_payments', 'التحقق من المدفوعات'), ('review_requests', 'مراجعة الطلبات'), ('generate_report', 'إنشاء تقرير'), ('manage_fees', 'إدارة الرسوم'), ('student_lookup', 'البحث عن طالب')], help_text='نوع الإجراء السريع', max_length=25, verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='description',
            field=models.CharField(help_text='وصف الإجراء السريع', max_length=200, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='icon_class',
            field=models.CharField(default='fas fa-cog', help_text='فئة CSS للأيقونة', max_length=50, verbose_name='فئة الأيقونة'),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل الإجراء نشط', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='name',
            field=models.CharField(help_text='اسم الإجراء السريع', max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='order',
            field=models.IntegerField(default=0, help_text='ترتيب عرض الإجراء', verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='required_permissions',
            field=models.JSONField(default=list, help_text='قائمة الصلاحيات المطلوبة', verbose_name='الصلاحيات المطلوبة'),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='url_pattern',
            field=models.CharField(help_text='نمط الرابط للإجراء', max_length=200, verbose_name='نمط الرابط'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'تسجيل دخول المستخدم'), ('logout', 'تسجيل خروج المستخدم'), ('request_approved', 'اعتماد طلب'), ('request_rejected', 'رفض طلب'), ('payment_verified', 'التحقق من دفعة'), ('payment_rejected', 'رفض دفعة'), ('document_uploaded', 'رفع مستند'), ('announcement_created', 'إنشاء إعلان'), ('notification_created', 'إنشاء إشعار'), ('report_generated', 'إنشاء تقرير'), ('fee_created', 'إنشاء رسوم'), ('user_created', 'إنشاء مستخدم'), ('user_modified', 'تعديل مستخدم'), ('other', 'نشاط آخر')], help_text='نوع النشاط المنجز', max_length=20, verbose_name='نوع النشاط'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='description',
            field=models.TextField(help_text='وصف تفصيلي للنشاط', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='عنوان IP للمستخدم', null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='بيانات إضافية حول النشاط', verbose_name='البيانات الوصفية'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='staff_member',
            field=models.ForeignKey(help_text='الموظف الذي قام بالنشاط', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='عضو الطاقم'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='المستخدم الذي تأثر بالنشاط', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستهدف'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت النشاط', verbose_name='الطابع الزمني'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='user_agent',
            field=models.TextField(blank=True, help_text='معلومات المتصفح', verbose_name='وكيل المستخدم'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء القالب', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='created_by',
            field=models.ForeignKey(help_text='الموظف الذي أنشأ القالب', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='description',
            field=models.TextField(help_text='وصف سير العمل', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل القالب نشط', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='name',
            field=models.CharField(help_text='اسم قالب سير العمل', max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='steps',
            field=models.JSONField(default=list, help_text='قائمة خطوات سير العمل', verbose_name='الخطوات'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='workflow_type',
            field=models.CharField(choices=[('request_processing', 'معالجة الطلبات'), ('payment_verification', 'التحقق من المدفوعات'), ('document_generation', 'إنشاء المستندات'), ('student_onboarding', 'تسجيل الطلاب الجدد'), ('fee_management', 'إدارة الرسوم')], help_text='نوع سير العمل', max_length=25, verbose_name='نوع سير العمل'),
        ),
    ]
