# Generated by Django 5.2.4 on 2025-08-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_panel', '0003_alter_dashboardstats_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfiguration',
            options={'ordering': ['category', 'key'], 'verbose_name': 'إعداد النظام', 'verbose_name_plural': 'إعدادات النظام'},
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='category',
            field=models.CharField(choices=[('general', 'الإعدادات العامة'), ('academic', 'الإعدادات الأكاديمية'), ('financial', 'الإعدادات المالية'), ('notification', 'إعدادات الإشعارات'), ('security', 'إعدادات الأمان')], help_text='فئة الإعداد', max_length=15, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء الإعداد', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='description',
            field=models.TextField(blank=True, help_text='وصف الإعداد', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل الإعداد نشط', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='key',
            field=models.CharField(help_text='مفتاح الإعداد', max_length=100, verbose_name='المفتاح'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='updated_by',
            field=models.ForeignKey(help_text='الموظف الذي قام بآخر تحديث', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='value',
            field=models.TextField(help_text='قيمة الإعداد', verbose_name='القيمة'),
        ),
    ]
