# Generated by Django 5.2.4 on 2025-08-28 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('enrollment_certificate', 'شهادة قيد'), ('schedule_modification', 'تعديل الجدول الدراسي'), ('semester_postponement', 'تأجيل الفصل الدراسي'), ('transcript', 'كشف الدرجات الرسمي'), ('graduation_certificate', 'شهادة التخرج'), ('other', 'أخرى')], help_text='نوع الخدمة المطلوبة', max_length=30, verbose_name='نوع الطلب')),
                ('title', models.CharField(help_text='عنوان مختصر للطلب', max_length=200, verbose_name='عنوان الطلب')),
                ('description', models.TextField(help_text='وصف تفصيلي للطلب', verbose_name='وصف الطلب')),
                ('status', models.CharField(choices=[('pending', 'في انتظار المراجعة'), ('in_review', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل'), ('more_info_needed', 'يحتاج معلومات إضافية')], default='pending', help_text='الحالة الحالية للطلب', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء الطلب', verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث')),
                ('rejection_reason', models.TextField(blank=True, help_text='سبب رفض الطلب إن وجد', verbose_name='سبب الرفض')),
                ('additional_info_request', models.TextField(blank=True, help_text='المعلومات الإضافية المطلوبة من الطالب', verbose_name='طلب معلومات إضافية')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', help_text='أولوية معالجة الطلب', max_length=10, verbose_name='الأولوية')),
                ('processed_by', models.ForeignKey(blank=True, help_text='الموظف الذي عالج الطلب', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت معالجته بواسطة')),
                ('student', models.ForeignKey(help_text='الطالب الذي قدم الطلب', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طلب خدمة',
                'verbose_name_plural': 'طلبات الخدمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='ملف المستند المرفق', upload_to='request_documents/', verbose_name='المستند')),
                ('document_name', models.CharField(help_text='اسم المستند المرفق', max_length=200, verbose_name='اسم المستند')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت رفع المستند', verbose_name='تاريخ الرفع')),
                ('request', models.ForeignKey(help_text='طلب الخدمة المرتبط بهذا المستند', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student_portal.servicerequest', verbose_name='طلب الخدمة')),
            ],
            options={
                'verbose_name': 'مستند الطلب',
                'verbose_name_plural': 'مستندات الطلبات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('enrollment_certificate', 'شهادة قيد'), ('transcript', 'كشف الدرجات الرسمي'), ('graduation_certificate', 'شهادة التخرج'), ('payment_receipt', 'إيصال دفع'), ('other', 'مستند آخر')], help_text='نوع المستند أو الشهادة', max_length=30, verbose_name='نوع المستند')),
                ('title', models.CharField(help_text='عنوان أو اسم المستند', max_length=200, verbose_name='عنوان المستند')),
                ('document_file', models.FileField(help_text='ملف المستند المرفق', upload_to='student_documents/', verbose_name='ملف المستند')),
                ('issued_date', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إصدار المستند', verbose_name='تاريخ الإصدار')),
                ('is_official', models.BooleanField(default=True, help_text='هل المستند رسمي', verbose_name='رسمي')),
                ('download_count', models.IntegerField(default=0, help_text='عدد مرات تحميل المستند', verbose_name='عدد التحميلات')),
                ('issued_by', models.ForeignKey(help_text='الموظف الذي أصدر المستند', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to=settings.AUTH_USER_MODEL, verbose_name='أصدر بواسطة')),
                ('student', models.ForeignKey(help_text='الطالب المالك للمستند', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'مستند الطالب',
                'verbose_name_plural': 'مستندات الطلاب',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='موضوع التذكرة', max_length=200, verbose_name='الموضوع')),
                ('description', models.TextField(help_text='وصف تفصيلي للمشكلة أو الاستفسار', verbose_name='الوصف')),
                ('category', models.CharField(choices=[('technical', 'الدعم الفني'), ('academic', 'الخدمات الأكاديمية'), ('financial', 'الخدمات المالية'), ('general', 'استفسار عام')], default='general', help_text='فئة التذكرة', max_length=20, verbose_name='الفئة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجل')], default='medium', help_text='أولوية التذكرة', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='open', help_text='حالة التذكرة الحالية', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء التذكرة', verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='الموظف المسؤول عن التذكرة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='مُسند إلى')),
                ('student', models.ForeignKey(help_text='الطالب الذي أنشأ التذكرة', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='نص الرد', verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت كتابة الرد', verbose_name='تاريخ الإنشاء')),
                ('is_internal', models.BooleanField(default=False, help_text='هل هذا الرد ملاحظة داخلية للموظفين فقط', verbose_name='ملاحظة داخلية')),
                ('responder', models.ForeignKey(help_text='الشخص الذي كتب الرد', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المجيب')),
                ('ticket', models.ForeignKey(help_text='التذكرة المرتبطة بهذا الرد', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='student_portal.supportticket', verbose_name='التذكرة')),
            ],
            options={
                'verbose_name': 'رد التذكرة',
                'verbose_name_plural': 'ردود التذاكر',
                'ordering': ['created_at'],
            },
        ),
    ]
