# Generated by Django 5.2.4 on 2025-08-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_alter_servicerequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Support'), ('academic', 'Academic Services'), ('financial', 'Financial Services'), ('general', 'General Inquiry')], default='general', max_length=20),
        ),
    ]
