# Generated by Django 5.2.4 on 2025-08-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0003_supportticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the document type', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the document type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document type is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('enrollment_certificate', 'Enrollment Certificate'), ('transcript', 'Official Transcript'), ('graduation_certificate', 'Graduation Certificate'), ('payment_receipt', 'Payment Receipt'), ('other', 'Other Document')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='document_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='student_portal.documenttype'),
        ),
    ]
