# Generated by Django 5.2.4 on 2025-08-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0004_documenttype_alter_studentdocument_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='document_type_new',
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('enrollment_certificate', 'Enrollment Certificate'), ('transcript', 'Official Transcript'), ('graduation_certificate', 'Graduation Certificate'), ('payment_receipt', 'Payment Receipt'), ('other', 'Other Document')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
