# Generated by Django 5.2.5 on 2025-08-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0006_documenttype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentType",
        ),
    ]
