# Generated by Django 5.2.4 on 2025-08-27 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0007_delete_documenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'مستند الطلب', 'verbose_name_plural': 'مستندات الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب خدمة', 'verbose_name_plural': 'طلبات الخدمات'},
        ),
        migrations.AlterModelOptions(
            name='studentdocument',
            options={'ordering': ['-issued_date'], 'verbose_name': 'مستند الطالب', 'verbose_name_plural': 'مستندات الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تذكرة دعم', 'verbose_name_plural': 'تذاكر الدعم'},
        ),
        migrations.AlterModelOptions(
            name='ticketresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'رد التذكرة', 'verbose_name_plural': 'ردود التذاكر'},
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='document',
            field=models.FileField(help_text='ملف المستند المرفق', upload_to='request_documents/', verbose_name='المستند'),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='document_name',
            field=models.CharField(help_text='اسم المستند المرفق', max_length=200, verbose_name='اسم المستند'),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='request',
            field=models.ForeignKey(help_text='طلب الخدمة المرتبط بهذا المستند', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student_portal.servicerequest', verbose_name='طلب الخدمة'),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت رفع المستند', verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='additional_info_request',
            field=models.TextField(blank=True, help_text='المعلومات الإضافية المطلوبة من الطالب', verbose_name='طلب معلومات إضافية'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء الطلب', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(help_text='وصف تفصيلي للطلب', verbose_name='وصف الطلب'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', help_text='أولوية معالجة الطلب', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='الموظف الذي عالج الطلب', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت معالجته بواسطة'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='سبب رفض الطلب إن وجد', verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('enrollment_certificate', 'شهادة قيد'), ('schedule_modification', 'تعديل الجدول الدراسي'), ('semester_postponement', 'تأجيل الفصل الدراسي'), ('transcript', 'كشف الدرجات الرسمي'), ('graduation_certificate', 'شهادة التخرج'), ('other', 'أخرى')], help_text='نوع الخدمة المطلوبة', max_length=30, verbose_name='نوع الطلب'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'في انتظار المراجعة'), ('in_review', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل'), ('more_info_needed', 'يحتاج معلومات إضافية')], default='pending', help_text='الحالة الحالية للطلب', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='student',
            field=models.ForeignKey(help_text='الطالب الذي قدم الطلب', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(help_text='عنوان مختصر للطلب', max_length=200, verbose_name='عنوان الطلب'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_file',
            field=models.FileField(help_text='ملف المستند المرفق', upload_to='student_documents/', verbose_name='ملف المستند'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('enrollment_certificate', 'شهادة قيد'), ('transcript', 'كشف الدرجات الرسمي'), ('graduation_certificate', 'شهادة التخرج'), ('payment_receipt', 'إيصال دفع'), ('other', 'مستند آخر')], help_text='نوع المستند أو الشهادة', max_length=30, verbose_name='نوع المستند'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='download_count',
            field=models.IntegerField(default=0, help_text='عدد مرات تحميل المستند', verbose_name='عدد التحميلات'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='is_official',
            field=models.BooleanField(default=True, help_text='هل المستند رسمي', verbose_name='رسمي'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='issued_by',
            field=models.ForeignKey(help_text='الموظف الذي أصدر المستند', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to=settings.AUTH_USER_MODEL, verbose_name='أصدر بواسطة'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إصدار المستند', verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(help_text='الطالب المالك للمستند', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='title',
            field=models.CharField(help_text='عنوان أو اسم المستند', max_length=200, verbose_name='عنوان المستند'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='الموظف المسؤول عن التذكرة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='مُسند إلى'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('technical', 'الدعم الفني'), ('academic', 'الخدمات الأكاديمية'), ('financial', 'الخدمات المالية'), ('general', 'استفسار عام')], default='general', help_text='فئة التذكرة', max_length=20, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء التذكرة', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.TextField(help_text='وصف تفصيلي للمشكلة أو الاستفسار', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجل')], default='medium', help_text='أولوية التذكرة', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='open', help_text='حالة التذكرة الحالية', max_length=15, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='student',
            field=models.ForeignKey(help_text='الطالب الذي أنشأ التذكرة', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(help_text='موضوع التذكرة', max_length=200, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاريخ ووقت آخر تحديث', verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت كتابة الرد', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='هل هذا الرد ملاحظة داخلية للموظفين فقط', verbose_name='ملاحظة داخلية'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='message',
            field=models.TextField(help_text='نص الرد', verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='responder',
            field=models.ForeignKey(help_text='الشخص الذي كتب الرد', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المجيب'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='ticket',
            field=models.ForeignKey(help_text='التذكرة المرتبطة بهذا الرد', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='student_portal.supportticket', verbose_name='التذكرة'),
        ),
    ]
