# Generated by Django 5.2.4 on 2025-08-28 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('fee_due', 'Fee Due Reminder'), ('document_ready', 'Document Ready'), ('general', 'General Template')], max_length=20)),
                ('subject_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('students', 'All Students'), ('staff', 'All Staff'), ('specific_major', 'Specific Major'), ('specific_year', 'Specific Academic Year'), ('specific_department', 'Specific Department')], default='all', max_length=20)),
                ('target_major', models.CharField(blank=True, max_length=100)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('target_department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الإشعار', max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(help_text='محتوى الإشعار', verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('info', 'معلومات'), ('warning', 'تحذير'), ('success', 'نجح'), ('error', 'خطأ'), ('announcement', 'إعلان')], default='info', help_text='نوع الإشعار', max_length=15, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', help_text='مستوى أولوية الإشعار', max_length=10, verbose_name='الأولوية')),
                ('is_read', models.BooleanField(default=False, help_text='هل تم قراءة الإشعار', verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء الإشعار', verbose_name='تاريخ الإنشاء')),
                ('read_at', models.DateTimeField(blank=True, help_text='تاريخ ووقت قراءة الإشعار', null=True, verbose_name='تاريخ القراءة')),
                ('expires_at', models.DateTimeField(blank=True, help_text='تاريخ ووقت انتهاء صلاحية الإشعار', null=True, verbose_name='تاريخ الانتهاء')),
                ('action_url', models.URLField(blank=True, help_text='رابط للإجراء المطلوب', verbose_name='رابط الإجراء')),
                ('action_text', models.CharField(blank=True, help_text='نص زر الإجراء', max_length=100, verbose_name='نص الإجراء')),
                ('recipient', models.ForeignKey(help_text='المستخدم المستلم للإشعار', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'إشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_announcements', models.BooleanField(default=True)),
                ('email_request_updates', models.BooleanField(default=True)),
                ('email_payment_updates', models.BooleanField(default=True)),
                ('email_fee_reminders', models.BooleanField(default=True)),
                ('app_announcements', models.BooleanField(default=True)),
                ('app_request_updates', models.BooleanField(default=True)),
                ('app_payment_updates', models.BooleanField(default=True)),
                ('app_fee_reminders', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
