# Generated by Django 5.2.4 on 2025-08-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'إشعارات'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, help_text='نص زر الإجراء', max_length=100, verbose_name='نص الإجراء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='رابط للإجراء المطلوب', verbose_name='رابط الإجراء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ ووقت إنشاء الإشعار', verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت انتهاء صلاحية الإشعار', null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='هل تم قراءة الإشعار', verbose_name='مقروء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='محتوى الإشعار', verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'معلومات'), ('warning', 'تحذير'), ('success', 'نجح'), ('error', 'خطأ'), ('announcement', 'إعلان')], default='info', help_text='نوع الإشعار', max_length=15, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', help_text='مستوى أولوية الإشعار', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت قراءة الإشعار', null=True, verbose_name='تاريخ القراءة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='المستخدم المستلم للإشعار', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='عنوان الإشعار', max_length=200, verbose_name='العنوان'),
        ),
    ]
